namespace: ernstov
placeholder-err-test:
  defines: runnable
  containers:
    placeholder-err-test:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: placeholder-err-test
      port: 8080
      protocol: tcp
